config/routes.rb
AppResidentApp::Application.routes.draw do


  get "static_pages/root"

  get "static_pages/admin"

  resources :user_chores
  post "user_chores/assign_group", to:  "user_chores#assign_group"
  resources :users, :only => [:create, :new, :show, :index]
  resource :session, :only => [:create, :destroy, :new]
  resources :chores

  root :to => "static_pages#root"
end

app/models/chore.rb
class Chore < ActiveRecord::Base
  attr_accessible :name, :description, :frequency
  has_many :user_chores

  DAY_OFFSETS = {
    'MON' => 0,
    'TUE' => 1,
    'WED' => 2,
    'THU' => 3,
    'FRI' => 4,
    'SAT' => 5,
    'SUN' => 6
  }

  def generate_user_chores weeks
    next_monday = Date.today.next_week
    days = self.frequency.split(',')
    chores = []

    (1..weeks).each do |week_index|
      days.each do |day|
       chores << self.user_chores.build(:date => next_monday + DAY_OFFSETS[day])
      end
      next_monday = next_monday.next_week
    end

    self.user_chores << chores
  end
end

app/models/cohort.rb
class Cohort < ActiveRecord::Base
  attr_accessible :name, :start_date
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :name, :current_resident
  attr_reader :password

  validates :password_digest, :presence => { :message => "Password can't be blank" }
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true
  validates :email, :presence => true

  after_initialize :ensure_session_token
  has_many :user_chores

  def self.non_admin_users
    where(:admin => false)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/models/user_chore.rb
class UserChore < ActiveRecord::Base
  attr_accessible :chore_id, :date, :user_id, :complete
  belongs_to :user
  belongs_to :chore
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  before_filter :require_current_user!
  before_filter :require_admin!, :only => :create

  def index
    @chores = Chore.all
  end

  def show
    @chore = Chore.find(params[:id])
  end

  def new
  end

  def create
    puts "here come params*************"
    p params
    @chore = Chore.new(params[:chore])
    if !@chore.save
      render :json => @chore.errors.full_messages
    else
      render :json => @chore
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_no_current_user!, :only => [:create, :new]
  before_filter :require_current_user!, :only => [:destroy]

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if user.nil?
      render :json => "Credentials were wrong"
    else
      self.current_user = user
      redirect_to root_url
    end
  end

  def destroy
    logout_current_user!
    redirect_to root_url
  end

  def new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :require_current_user!
  def root
    @user_json = User.all.to_json(:only => [:id, :name])
    @chore_json = Chore.all.to_json(:only => [:id, :name])
  end

  def admin
  end
end

app/controllers/user_chores_controller.rb
class UserChoresController < ApplicationController
  def index
    @user_chores = UserChore.includes(:user, :chore).order(:date)
  end

  def show
  end

  def create
    @user_chore = UserChore.new(params[:user_chore])

    unless @user_chore.save
      flash.now = @user_chore.errors.full_messages
    end

    redirect_to chore_url @user_chore.chore
  end

  def update
    @user_chore = UserChore.find(params[:id])
    p params[:user_chore]
    if @user_chore.update_attributes(params[:user_chore])
      status = 200
    else
      status = 422
    end
    render :json => @user_chore, :status => status
  end

  def assign_group
    @user_chores = UserChore.where(:id => params[:user_chore_ids])
    random_users = User.non_admin_users.pluck(:id).sample(@user_chores.count)
    @user_chores.each_with_index do |chore, index|
      chore.user_id = random_users[index]
      chore.save
    end
    #NEED TO make this randomish, but fair. Should assign to deserving users.
    render :json => @user_chores.include(:user, :chore)

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, :only => [:show]
  before_filter :require_no_current_user!, :only => [:create, :new]

  def index
    @users = User.where(:admin => false)
    respond_to do |format|
      format.html
      format.json { render :json => @users }
    end
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      self.current_user = @user
      redirect_to root_url
    else
      render :json => @user.errors.full_messages
    end
  end

  def new
    @user = User.new
  end

  def show
    if params.include?(:id)
      @user = User.find(params[:id])
    else
      redirect_to user_url(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chores_controller_helper.rb
module ChoresControllerHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def current_user=(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout_current_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to new_session_url if current_user.nil?
  end

  def require_no_current_user!
    redirect_to user_url(current_user) unless current_user.nil?
  end
  def require_admin!
    redirect_to root_url unless current_user && current_user.admin?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_chores_helper.rb
module UserChoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chores/_chore_form.html.erb
<form action="<%=chores_url%>" method="post" accept-charset="utf-8">
  <input type="hidden" 
    name="authenticity_token" 
    value="<%=form_authenticity_token%>"  />
  <label for="chore_name">Chore</label>
  <input 
    type="text" 
    name="chore[name]" 
    id="chore_name" 
    value="" 
    placeholder="chore name..." />
</form>

app/views/chores/index.html.erb
<h1>Chores!</h1>
<ul>
<% @chores.each do |chore| %>
<li><%=link_to chore.name, chore_url(chore) %></li>
<% end %>
</ul>

<% if current_user && current_user.admin %>
  <%= render 'chore_form' %>
<% end %>

app/views/chores/new.html.erb
<h1>ChoresController#new</h1>
<p>Find me in app/views/chores_controller/new.html.erb</p>

app/views/chores/show.html.erb
<h1><%= @chore.name %></h1>
<ul>
  <%@chore.user_chores.each do |user_chore|%>
  <li><%="#{user_chore.date}"%>
    <% if user_chore.user_id? %>
      <%= user_chore.user.name %>
    <% else %>
      <%= button_to "Assign Chore", chores_url %>
    <% end %>
  </li>
  <%end%>
</ul>
<p>
<%= @chore.to_json %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App Academy Residents</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <header>
      <nav class="navbar navbar-default" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#demo-project-navbar-collapse-1">
          &#9776;
        </button>
        <%= link_to "App Academy Residents", '/#', :class => "navbar-brand"%>
      </div>
      <div class="collapse navbar-collapse" id="demo-project-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-left">
          <% if current_user %>
          <li><%= link_to "Chores", '/#chores' %></li>
          <li><%= link_to "Peeps", users_url %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <%if current_user%>
          <li>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%=current_user.email%><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="<%=user_url current_user%>">Profile</a></li>
            <li class="divider"></li>
            <li><%= link_to "Log Out", session_url, method: :delete %></li>

          </ul>
          </li>
          <% else %>
          <li>
          <%= link_to "Log In", new_session_url %>
          </li>
          <% end %>
        </ul>
      </div>
      </nav>
      </header>
      <div class="col col-xs-12">
        <%= yield %>
      </div>
    </div>
  </body>

</html>

app/views/shared/_form.html.erb
<div class="row">
  <div class="col-xs-4">
    <h1><%= message %> </h1>
    <form action="<%= action %>" method="<%= method %>">
      <div class="form-group">
        <input
        name="authenticity_token"
        type="hidden"
        value="<%= form_authenticity_token %>">

        <% if @user && !(@user.persisted?) %>
          <label for="user_name">Name</label>
          <input
          class="form-control"
          id="user_name"
          name="user[name]"
          type="text">
          <br>
          <% unless Cohort.all.empty? %> 
            <label for="user_cohort">Cohort</label>
            <select
            class="form-control"
            id="user_cohort"
            name="user[cohort_id]">
              <% Cohort.all.each do |cohort| %>
                <option value="<%= cohort.id %>"><%= cohort.name %></option>
              <% end %>
            </select>
            <br>
          <% end %>

          <label for="user_moved_in">Move-In Date</label>
          <input type="date"
          id="user_moved_in"
          name="user[moved_in]">
          <br>

        <% end %>

        <label for="user_email">Email</label>
        <input
        class="form-control"
        id="user_email"
        name="user[email]"
        type="text">
        <br>

        <label for="user_password">Password</label>
        <input
        class="form-control"
        id="user_password"
        name="user[password]"
        type="password">
        <br>

        <button type="submit" class="btn btn-primary"><%=message%></button>
        <p>
      </div>
    </form>
  </div>
</div>

app/views/static_pages/admin.html.erb
<h1>StaticPages#admin</h1>
<p>Find me in app/views/static_pages/admin.html.erb</p>

app/views/static_pages/root.html.erb
<div id="content">
</div>

<script>
  $(document).ready(function(){
    AppResidentApp.admin = <%=current_user ? current_user.admin : false %>;
    AppResidentApp.user = <%=current_user.to_json(:only => [:id, :name, :email, :admin]).html_safe%>
    AppResidentApp.users = <%=@user_json.html_safe%>
    AppResidentApp.chores = <%=@chore_json.html_safe%>
    AppResidentApp.initialize();
  });
</script>

app/views/user_chores/show.html.erb
<h1>UserChores#show</h1>
<p>Find me in app/views/user_chores/show.html.erb</p>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
    <li><%= link_to "#{user.name} (#{user.email})", "/#users/#{user.id}" %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% action = (@user.persisted? ? user_url(@user) : users_url) %>
<% method = (@user.persisted? ? "put" : "post") %>
<% message = (@user.persisted? ? "Update user" : "Create user") %>

<%= render "shared/form", 
    :user => @user, 
    :action => action, 
    :method => method, 
    :message => message %>

<p>Already have an account? <a href="<%=new_session_url%>">Log In Here</a></p>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<p>Hello, dear user!</p>